name: CI/CD

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Linter
        run: flake8 server.py tests.py

      - name: Run Unit Tests
        run: pytest tests.py
       